language: ruby
services:
  - mysql
  - redis
rvm:
  - "1.9.3"
script: bundle exec rspec spec
before_script:
  - mysql -e 'create database sugar_test;'
  - cp config/database.yml.dist config/database.yml
  - cp config/initializers/sugar.rb.dist config/initializers/sugar.rb